image: docker:latest
services:
  - docker:dind
####
stages:
  - build
  - deploy

variables:
  CONTAINER_IMAGE: delacroa1/go:latest

build:
  stage: build
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} delacroa1/go:latest
    - docker push delacroa1/go
    - echo 1

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
#    - kubectl config set-cluster k8s --server="${SERVER}"
    - echo "$K8S_SECRET_CERTIFICATE_AUTHORITY_DATA" > "$(pwd)/kube.ca.pem"
    - kubectl config set-cluster github --server="$SERVER" --certificate-authority="$(pwd)/kube.ca.pem"
#    - kubectl config set clusters.k8s.certificate-authority-data "${K8S_SECRET_CERTIFICATE_AUTHORITY_DATA}"
    - kubectl config set-credentials gitlab --token="${K8S_SECRET_USER_TOKEN}"
    - kubectl config set-context default --cluster=github --user=gitlab
    - kubectl config use-context default
    - kubectl apply -f deployment.yaml
    - kubectl get pods

